### ISSUE TITLE
[Refactor] Design component refactoring

### ISSUE THREAD

**Issue by jinyoung5497** [jinyoung5497/shopease-ecommerce-project#17]
## 💡 Feature Issue

Design component내 코드들 리팩토링
## 🌿  To-do

- [x] cva 라이브러리 사용한 variants 별 color 구현
- [x] dropdown full width size css 수정
- [x] modal submit 버튼: submit하고 모달 닫기 기능 구현
