### ISSUE TITLE
[REFACTOR] refactoring modal component as controlled component

### ISSUE THREAD

**Issue by jinyoung5497** [jinyoung5497/shopease-ecommerce-project#39]
## 💡 Feature Issue

[REFACTOR] refactoring modal component as controlled component
## 🌿  To-do

- [x] refactoring modal component as controlled component
- [x] modal component separation
- [x] component shape function separation
